### ISSUE TITLE
BUG: Routing issue

### ISSUE THREAD

**Issue by KIET7UKE** [KIET7UKE/BookYourPandit.com#13]
Issue: When we click on the logo on the services page. It doesn't route to the main home page. The routing is not happening there.

Steps to produce:
1. Run the server
2. Click on View All Services
3. Click on the logo

![image](https://user-images.githubusercontent.com/76551267/233487229-8877e7db-4b70-43ab-a2cc-5f5479f96123.png)

**Comment by Alve2000** [comment]
Okay, ill work on that.

**Comment by capitan-beto** [comment]
Hello! I'd like to work on it if it's ok to you

**Comment by KIET7UKE** [comment]
@capitan-beto Thanks, But @Alve2000 is working with me on this project. Stay updated within a week we will open more issues.

**Comment by KIET7UKE** [comment]
> Okay, ill work on that.

Fix this asap.

**Comment by Alve2000** [comment]
I have fixed the routing problem.
Check PR #11

**Comment by KIET7UKE** [comment]
> I have fixed the routing problem.
> Check PR with the commit [logo_routing](https://github.com/KIET7UKE/BookYourPandit.com/pull/11/commits/568cf89486db501e6598aa8d2a091cd7abdbc77f) #11

Cool.
